# Generated by Django 4.2 on 2025-06-30 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin título', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('grafico', 'Gráfico'), ('simplex', 'Simplex')], default='grafico', max_length=20)),
                ('datos', models.TextField(blank=True, null=True)),
                ('objetivo', models.CharField(choices=[('max', 'Maximizar'), ('min', 'Minimizar')], default='max', max_length=10)),
                ('funcion_objetivo', models.CharField(max_length=200)),
                ('restricciones', models.TextField(help_text='Una por línea. Ej: 2x+3y<=6')),
                ('limites', models.CharField(help_text='Ej: x>=0, y>=0', max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
