"""
Django settings for MetodoGrafico project.

Generated by 'django-admin startproject' using Django 5.0.6.
"""

from pathlib import Path
import os
import pymysql
pymysql.install_as_MySQLdb()


# Ruta base del proyecto
BASE_DIR = Path(__file__).resolve().parent.parent

# Clave secreta (solo para desarrollo; en producción, almacénala de forma segura)
SECRET_KEY = 'django-insecure-jtv)v$jfsqo)97m-34&($b$fa=7u6g73hx-9so@af8amn$l&5^'

# Activa el modo de depuración (solo para desarrollo)
DEBUG = True

ALLOWED_HOSTS = [] 

# Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'grafico',             # Mi app creada
    'widget_tweaks',       # Para personalizar formularios en plantillas
]

# Redirección al cerrar sesión
LOGOUT_REDIRECT_URL = ''
# Redirección al intentar acceder sin login
LOGIN_URL = '/login/'

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Enrutador principal
ROOT_URLCONF = 'GraficoMetodo.urls'

# Plantillas HTML
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'grafico' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n', 
            ],
        },
    },
]

# Configuración WSGI
WSGI_APPLICATION = 'GraficoMetodo.wsgi.application'

# Base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_graficometodo',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Validadores de contraseña
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuración de idioma y zona horaria
LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/El_Salvador' 

USE_I18N = True
USE_L10N = True
USE_TZ = True 

# Idiomas disponibles en la interfaz
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

# Ruta donde se guardarán los archivos .po y .mo para traducciones
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Archivos estáticos (CSS, JS, imágenes)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Campo por defecto para claves primarias
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
